server:
  address: 127.0.0.1
  port: 9130

jmx:
  - cluster: hadoop_cluster
    component: hdfs
    service: namenode
    url: http://localhost:9870/jmx

  - cluster: hadoop_cluster
    component: yarn
    service: resourcemanager
    url: http://localhost:8088/jmx
